name: Deploy on DigitalOcean
on: 
  push:
    branches:
      - main

jobs:  
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull latest version
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          make pull-nl
